let cart = JSON.parse(localStorage.getItem("cart")) || [];

function openCart() {
  document.getElementById("cart-drawer").classList.add("open");
}

function addToCart(product) {
  cart.push(product);
  localStorage.setItem("cart", JSON.stringify(cart));
  document.getElementById("cart-count").innerText = cart.length;
}

function goToCheckout() {
  window.location.href = "checkout.html";
}
